# 10 数据连接

In [1]:
import pandas as pd
import numpy as np

df_obj1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                        'data1' : np.random.randint(0,10,7)})
df_obj2 = pd.DataFrame({'key': ['a', 'b' ,'d'],
                        'data2' : np.random.randint(0,10,3)})

print(df_obj1)
print('-'*50)
print(df_obj2)

  key  data1
0   b      4
1   b      4
2   a      9
3   c      2
4   a      0
5   a      2
6   b      6
--------------------------------------------------
  key  data2
0   a      1
1   b      0
2   d      0

In [2]:
#默认连接使用相同的列名，连接方式是内连接
pd.merge(df_obj1, df_obj2)

  key  data1  data2
0   b      4      0
1   b      4      0
2   a      9      1
3   a      0      1
4   a      2      1
5   b      6      0

In [3]:
#左df和右df都拿索引连接
pd.merge(df_obj1, df_obj2,left_index=True,right_index=True)

  key_x  data1 key_y  data2
0     b      4     a      1
1     b      4     b      0
2     a      9     d      0

In [4]:
#左表和右表都拿key列来连接
pd.merge(df_obj1, df_obj2, on='key')

  key  data1  data2
0   b      4      0
1   b      4      0
2   a      9      1
3   a      0      1
4   a      2      1
5   b      6      0

In [5]:
# 更改列名
df_obj1 = df_obj1.rename(columns={'key':'key1'})
df_obj2 = df_obj2.rename(columns={'key':'key2'})

In [6]:
df_obj1

  key1  data1
0    b      4
1    b      4
2    a      9
3    c      2
4    a      0
5    a      2
6    b      6

In [7]:
df_obj2

  key2  data2
0    a      1
1    b      0
2    d      0

In [8]:
#左表以key1来连接，右表以key2来连接
pd.merge(df_obj1, df_obj2, left_on='key1', right_on='key2')

  key1  data1 key2  data2
0    b      4    b      0
1    b      4    b      0
2    a      9    a      1
3    a      0    a      1
4    a      2    a      1
5    b      6    b      0

In [9]:
#全外连接
pd.merge(df_obj1, df_obj2, left_on='key1', right_on='key2', how='outer')  #全外连接

  key1  data1 key2  data2
0    a    9.0    a    1.0
1    a    0.0    a    1.0
2    a    2.0    a    1.0
3    b    4.0    b    0.0
4    b    4.0    b    0.0
5    b    6.0    b    0.0
6    c    2.0  NaN    NaN
7  NaN    NaN    d    0.0

In [10]:
#left join 等价于 left  join
pd.merge(df_obj1, df_obj2, left_on='key1', right_on='key2', how='left')

  key1  data1 key2  data2
0    b      4    b    0.0
1    b      4    b    0.0
2    a      9    a    1.0
3    c      2  NaN    NaN
4    a      0    a    1.0
5    a      2    a    1.0
6    b      6    b    0.0

In [11]:
# right等价于数据库的right join
pd.merge(df_obj1, df_obj2, left_on='key1', right_on='key2', how='right')

  key1  data1 key2  data2
0    a    9.0    a      1
1    a    0.0    a      1
2    a    2.0    a      1
3    b    4.0    b      0
4    b    4.0    b      0
5    b    6.0    b      0
6  NaN    NaN    d      0

In [12]:
# 处理重复列名
df_obj1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                        'data' : np.random.randint(0,10,7)})
df_obj2 = pd.DataFrame({'key': ['a', 'b', 'd'],
                        'data' : np.random.randint(0,10,3)})
#给相同的数据列添加后缀
print(pd.merge(df_obj1, df_obj2, on='key', suffixes=('_left', '_right')))

  key  data_left  data_right
0   b          0           8
1   b          1           8
2   a          8           5
3   a          0           5
4   a          8           5
5   b          4           8

In [13]:
# 按索引连接
df_obj1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                        'data1' : np.random.randint(0,10,7)})
df_obj2 = pd.DataFrame({'data2' : np.random.randint(0,10,3)}, index=['a', 'b', 'd'])
print(df_obj1)
print(df_obj2)

  key  data1
0   b      7
1   b      1
2   a      9
3   c      7
4   a      6
5   a      8
6   b      7
   data2
a      3
b      3
d      6

In [14]:
print(pd.merge(df_obj1, df_obj2, left_on='key', right_index=True))

  key  data1  data2
0   b      7      3
1   b      1      3
2   a      9      3
4   a      6      3
5   a      8      3
6   b      7      3

In [15]:
pd.merge(df_obj2,df_obj1, left_index=True, right_on='key')

   data2 key  data1
2      3   a      9
4      3   a      6
5      3   a      8
0      3   b      7
1      3   b      1
6      3   b      7